const FIVE_MINUTES_IN_SECONDS = 300;
const SIXTY_MINUTES_IN_SECONDS = 3600;
const TWO_HOURS_IN_SECONDS = 7200;
const THIRTY_DAYS_IN_SECONDS = 259200;

module.exports = {
  FIVE_MINUTES_IN_SECONDS,
  SIXTY_MINUTES_IN_SECONDS,
  TWO_HOURS_IN_SECONDS,
  THIRTY_DAYS_IN_SECONDS
};
